version: '3.7'

services:
  maildev:
    image: maildev/maildev:1.1.0
    ports:
#      - "1080:80"
      - "1025:25"
  nginx:
    image: nginx:1.18.0-alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs/:/etc/nginx/certs
