version: "3.3"

services:
  serilogdemo1:
    container_name: serilogdemo1
    image: serilogdemo1:0.1
    build:
     context: .
     dockerfile: Dockerfile 
     args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
    ports:
      - "5100:5100"
      - "5101:5101"
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ASPNETCORE_URLS=https://*:5101;http://*:5100"
  seq1:
    container_name: seq1
    image: datalust/seq
    ports:
      - "5341:80"
    environment:
      - "ACCEPT_EULA=Y"
