apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: app1-svc
  namespace: {{APP_NAMESPACE}}
spec:
  podSelector:
    matchLabels:
      app: app1
  listeners:
    - portMapping:
        port: 2080
        protocol: http
  serviceDiscovery:
    dns:
      hostname: app1-svc.{{APP_NAMESPACE}}.svc.cluster.local
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: app2-svc
  namespace: {{APP_NAMESPACE}}
spec:
  podSelector:
    matchLabels:
      app: app2
  listeners:
    - portMapping:
        port: 80
        protocol: http
  serviceDiscovery:
    dns:
      hostname: app2-svc.{{APP_NAMESPACE}}.svc.cluster.local
