apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: app1-svc
  namespace: {{APP_NAMESPACE}}
spec:
  awsName: app1-svc.{{APP_NAMESPACE}}.svc.cluster.local
  provider:
    virtualRouter:
      virtualRouterRef:
        name: app1-svc-virtual-router
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: app2-svc
  namespace: {{APP_NAMESPACE}}
spec:
  awsName: app2-svc.{{APP_NAMESPACE}}.svc.cluster.local
  provider:
    virtualRouter:
      virtualRouterRef:
        name: app2-svc-virtual-router
