apiVersion: v1
kind: Namespace
metadata:
  name: {{APP_NAMESPACE}}
  # enable app mesh controller to inject Envoy onto each pode
  labels:
    mesh: {{MESH_NAME}}
    appmesh.k8s.aws/sidecarInjectorWebhook: enabled
