version: '3.8'

services:
  demo1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:80
      - 5001:443
    environment:
      - ENV_AT_RUNTIME=yes
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=p@ssw0rd
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/demo1.pfx
    volumes:
      - ./certs:/https:ro